version: '3.8'

services:
 web:
  build: .
  command: python app.py
  ports:
  - "5000:5000"
  volumes:
  - .:/app
  - ./conf/base_conf.py:/app/conf/base_conf.py

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=root
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
  cap_add:
  - SYS_NICE

volumes:
  mysql:
  mysql_config:

